PRESET_BASE: mainnet
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 3
MIN_GENESIS_TIME: 0
GENESIS_DELAY: 15
GENESIS_FORK_VERSION: 0x00000000
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_EPOCH: 0
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 8

